version: '3.7'
services:
    db:
        container_name: db
        image: mysql
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: symfony
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        networks:
            - db
    php:
        container_name: php-fpm
        build: ./php-fpm
        ports:
            - "9002:9001"
        volumes:
            - ./backend_symfony:/var/www/symfony:cached
        depends_on: 
            - db
        networks:
            - db
            - php
    nginx:
        container_name: nginx
        build: ./nginx
        ports:
            - "82:80"
        depends_on: 
            - php
        networks:
            - php
        volumes:
            - ./backend_symfony:/var/www/symfony:cached

networks:
    db:
    php: